In [2]:
cd ..

/Users/hao/workspace/hpi_de/4th_Semester/Online Learning/rl-4-self-repair


In [3]:
import logging
import time
import numpy as np
from tqdm.auto import tqdm
import seaborn as sns
sns.set()
import matplotlib.pyplot as plt
from algorithm_analysis.a2c import Model, A2CAgent
from envs.broken_components import BrokenComponentsEnv
from algorithm_analysis.benchmark import BROKEN_COMPONENTS_LIST

In [4]:
def plot_reward_histories(reward_histories, broken_component_list=None):
    for i, rewards_history in enumerate(reward_histories):
        plt.figure(i)
        ax = sns.lineplot(np.arange(len(rewards_history)), rewards_history)
        if broken_component_list:
            ax.set_title('Number of broken components: {}'.format(len(broken_component_list[i])))

In [ ]:
reward_histories = []

for i, broken_components in enumerate(tqdm(BROKEN_COMPONENTS_LIST[:4], desc='Broken Components Loop: ')):
    env = BrokenComponentsEnv(broken_components, state_as_vec=True)
    model = Model(num_actions=env.action_space.n)
    agent = A2CAgent(model, lr=7e-3, gamma=0.99, value_c=0.5, entropy_c=1e-4)
    
    rewards_history = agent.train(env, batch_sz=64, updates=50*len(broken_components))
    reward_histories.append(rewards_history)
    #plt.figure(i)
    #ax = sns.lineplot(np.arange(len(rewards_history)), rewards_history)
    #ax.set_title('Number of broken components: {}'.format(len(broken_components)))

plot_reward_histories(reward_histories, BROKEN_COMPONENTS_LIST)

In [ ]:
reward_histories = []

for i, broken_components in enumerate(tqdm(BROKEN_COMPONENTS_LIST[4:8], desc='Broken Components Loop: ')):
    env = BrokenComponentsEnv(broken_components, state_as_vec=True)
    model = Model(num_actions=env.action_space.n)
    agent = A2CAgent(model, lr=7e-3, gamma=0.99, value_c=0.5, entropy_c=1e-4)
    
    rewards_history = agent.train(env, batch_sz=64, updates=50*len(broken_components))
    reward_histories.append(rewards_history)
    #plt.figure(i)
    #ax = sns.lineplot(np.arange(len(rewards_history)), rewards_history)
    #ax.set_title('Number of broken components: {}'.format(len(broken_components)))

plot_reward_histories(reward_histories, BROKEN_COMPONENTS_LIST)

In [ ]:
reward_histories = []

for i, broken_components in enumerate(tqdm(BROKEN_COMPONENTS_LIST[8:12], desc='Broken Components Loop: ')):
    env = BrokenComponentsEnv(broken_components, state_as_vec=True)
    model = Model(num_actions=env.action_space.n)
    agent = A2CAgent(model, lr=7e-3, gamma=0.99, value_c=0.5, entropy_c=1e-4)
    
    rewards_history = agent.train(env, batch_sz=64, updates=50*len(broken_components))
    reward_histories.append(rewards_history)
    #plt.figure(i)
    #ax = sns.lineplot(np.arange(len(rewards_history)), rewards_history)
    #ax.set_title('Number of broken components: {}'.format(len(broken_components)))

plot_reward_histories(reward_histories, BROKEN_COMPONENTS_LIST)

In [ ]:
reward_histories = []

for i, broken_components in enumerate(tqdm(BROKEN_COMPONENTS_LIST[12:], desc='Broken Components Loop: ')):
    env = BrokenComponentsEnv(broken_components, state_as_vec=True)
    model = Model(num_actions=env.action_space.n)
    agent = A2CAgent(model, lr=7e-3, gamma=0.99, value_c=0.5, entropy_c=1e-4)
    
    rewards_history = agent.train(env, batch_sz=64, updates=50*len(broken_components))
    reward_histories.append(rewards_history)
    #plt.figure(i)
    #ax = sns.lineplot(np.arange(len(rewards_history)), rewards_history)
    #ax.set_title('Number of broken components: {}'.format(len(broken_components)))

plot_reward_histories(reward_histories, BROKEN_COMPONENTS_LIST)

In [ ]:
plot_reward_histories(reward_histories, BROKEN_COMPONENTS_LIST)

In [1]:
reward_histories

NameError: name 'reward_histories' is not defined

In [ ]:
reward_histories

In [6]:
t = np.arange(3, 30, 2)

In [8]:
t[:4]

array([3, 5, 7, 9])

In [9]:
t[4:8]

array([11, 13, 15, 17])

In [11]:
t[8:12]

array([19, 21, 23, 25])

In [12]:
t[12:]

array([27, 29])